### ISSUE TITLE
[BUG] Casual level icon on the main menu cuts out on both sides

### ISSUE THREAD

**Issue by MrConeMan** [CriticalFlaw/TF2HUD-Fixes#302] opened 2024-11-30 09:23 UTC
**Describe the issue.**
On the main menu screen and this is only usually noticeable on higher casual levels but on both sides the icon sorta cuts off if you gain a higher level.

* Resolution: 1920x1080

**Screenshots**
![image](https://github.com/user-attachments/assets/14a30b98-95be-42c6-b66f-3ccbaf2bd154)
![image](https://github.com/user-attachments/assets/59929653-807b-407b-a6cc-ad44be6dc8af)

**Comment by MrConeMan** [comment] 2024-12-01 16:01
@CriticalFlaw Figured out a way to patch this
In pvprankpanel.res in the "RankModel" section just change the "tall" value to 90 and the "fov" value to 60
![image](https://github.com/user-attachments/assets/2096b9ba-a9c3-4743-bb4c-fc4414a2b3f6)
This is what it should look like now if these changes are made

**Comment by CriticalFlaw** [comment] 2024-12-02 01:07
It's very odd because on my side in 1920x1080 the medal appears fine and has a large bounding box as-is. I'm a bit cautious about increasing its fov because it may become comically large in lower resolution.

![image](https://github.com/user-attachments/assets/16530f44-f37f-4155-9d5d-44c8edd0c938)

**Comment by valeriedesumo** [comment] 2024-12-16 16:47
This is a bug with the custom HUD, not vanilla. On 1920x1080, I can confirm that the model was getting cut off when using the latest files on github, and that the suggested fix works, as well as the original values of p0.12 and 70
Current HUD:
![image](https://github.com/user-attachments/assets/7073a220-d1bc-4eb1-9978-42923e720ecb)
Pull Request:
![image](https://github.com/user-attachments/assets/285c406d-843d-4ec4-8a2a-18281289cdc0)

**Comment by CriticalFlaw** [comment] 2024-12-22 21:23
I'm trying to recall but there was a particular reason the medal was tweaked from the original. For now I've merged in #303 to see if that resolves the reported issue. @MrConeMan please re-test and let me know if it looks good on your end.

**Closed** 2024-12-23 02:36 UTC
Labels: bug report
